exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('recipes').del()
    .then(function () {
      // Inserts seed entries
      return knex('recipes').insert([
        {id: 1, title: 'PB&J Overnight Oats', meal_type: 'Breakfast', serving_size: 2, difficulty_level: 'Beginner', cooking_time_in_minutes: 15,
        ingredients: '⅔ cup rolled oats(65 g)\n\n⅔ cup milk(160 mL) of your choice\n\n½ cup vanilla greek yogurt(120 g)\n\n1 tablespoon strawberry jam\n\n3 tablespoons nut butter\n\n½ teaspoon vanilla extract\n\n1 teaspoon chia seed, optional\n\nstrawberry, quartered, to serve',
        instructions: 'In a mason jar or sealable container, add the oats, milk, yogurt, jam, nut butter, vanilla extract, chia seeds, and strawberries, and stir together.\n\nSeal and place in the refrigerator overnight for up to five days.\n\nTop with additional strawberries,if desired. Enjoy!',
        image_url: 'https://minimalistbaker.com/wp-content/uploads/2015/07/Peanut-Butter-Overnight-Oats-SQUARE.jpg'},
        {id: 2, title: 'Curry Noodle Soup', meal_type: 'Lunch', serving_size: 6, difficulty_level: 'Intermediate', cooking_time_in_minutes: 30,
        ingredients: '2 tablespoons refined coconut oil\n\n3 cloves garlic, minced\n\n1 tablespoon ginger, minced\n\n2 ½ tablespoons red curry paste\n\n15 oz coconut milk (440 mL), 1 can\n\n3 cups vegetable broth (720 mL) \n\n1 tablespoon agave \n\n8 oz rice noodle (225 g)\n\n7 oz tofu (200 g), cubed\n\n2 cups broccoli floret (300 g)\n\n1 red bell pepper, thinly sliced\n\n1 tablespoon lime juice\n\nsalt, to taste\n\nfresh cilantro, to serve',
        instructions: 'In a large pot, melt the coconut oil over medium heat. Once the oil begins to shimmer, add the garlic and ginger and cook for 2-3 minutes, until fragrant.\n\nAdd the red curry paste and cook another 2-3 minutes. \n\nAdd the coconut milk and stir well until the curry paste is evenly distributed. Add the vegetable broth and bring to a boil.\n\nOnce boiling, add the agave and rice noodles, and cook for 2 minutes, stirring frequently to prevent the noodles from sticking together.\n\nAdd the tofu, broccoli, and bell pepper, and stir to combine. Cook for 3-5 more minutes, until the noodles are cooked and the broccoli is tender.\n\nStir in the lime juice and add salt to taste.\n\nGarnish with cilantro and serve immediately.\n\nEnjoy!',
        image_url: 'https://lepetiteats.com/wp-content/uploads/2020/03/IMG_8149.jpg'},
        {id: 3, title: 'Teriyaki Chicken', meal_type: 'Dinner', serving_size: 4, difficulty_level: 'Intermediate', cooking_time_in_minutes: 20, ingredients: '500 g (1lb) boneless skinless chicken breasts cubed\n\n1-2 tsp sesame oil\n\n½ cup soy sauce\n\n¼ cup Sake/Mirin (optional, replace with water)\n\n¼ cup rice vinegar\n\n2 tbsp honey\n\n2 tbsp brown sugar\n\n1 garlic cloves crushed\n\n1 tsp crushed fresh ginger\n\nsesame seeds to serve', instructions: 'Heat a large frying pan over high heat. \n\nPat the chicken breast pieces dry with paper towels. \n\nAdd the sesame oil to the pan followed by the chicken. Brown the chicken well on all sides then remove from the pan and set aside.\n\nCombine the remaining ingredients except for the sesame seeds. Pour into the pan. \n\nAllow the sauce to come to a boil and cook for 1-2 minutes until it starts to thicken then add the chicken and its resting juices back into the pan. \n\nAllow to cook for 4-5 minutes until the chicken is cooked through and the sauce is sticky and coating the chicken. \n\nSprinkle over the sesame seeds and serve.',
        image_url: 'https://princesspinkygirl.com/wp-content/uploads/2021/05/crockpot-teriyaki-chicken-57-square-1200.jpg'},
        {id: 4, title: 'Sushi', meal_type: 'Lunch or Dinner', serving_size: 6, difficulty_level: 'Beginner', cooking_time_in_minutes: 15, ingredients: '6 sheets sushi seaweed aka nori\n\n1 batch prepared sushi rice\n\n1/2 lb sushi-grade raw salmon or desired raw fish of choice\n\n4 oz cream cheese sliced into strips\n\n1 avocado sliced\n\nsoy sauce for serving', instructions: 'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle. \n\nLayer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
        image_url: 'https://www.irishtimes.com/polopoly_fs/1.4404396.1604957315!/image/image.jpg_gen/derivatives/ratio_1x1_w1200/image.jpg'},
        {id: 5, title: 'Fish Tacos', meal_type: 'Lunch', serving_size: 4, difficulty_level: 'Beginner', cooking_time_in_minutes: 35, ingredients: '3 tbsp. extra-virgin olive oil\n\nJuice of 1 lime\n\n2 tsp. chili powder\n\n1 tsp. paprika\n\n1/2 tsp. ground cumin\n\n1/2 tsp. cayenne pepper\n\n1 1/2 lb. cod (or other flaky white fish)\n\n1/2 tbsp. vegetable oil\n\nKosher salt\n\nFreshly ground black pepper\n\n8 corn tortillas\n\n1 avocado, diced\n\nLime wedges, for serving\n\nSour cream, for serving\n\n---------------------\n\nFOR THE CORN SLAW\n\n1/4 c. mayonnaise\n\nJuice of 1 lime\n\n2 tbsp. freshly chopped cilantro\n\n1 tbsp. honey\n\n2 c. shredded purple cabbage\n\n1 c. corn kernels\n\n1 jalapeño, minced', instructions: 'In a medium shallow bowl, whisk together olive oil, lime juice, paprika, chili powder, cumin, and cayenne. \n\nAdd cod, tossing until evenly coated. Let marinate 15 minutes. \n\nMeanwhile, make slaw: In a large bowl, whisk together mayonnaise, lime juice, cilantro, and honey. Stir in cabbage, corn, and jalapeño. Season with salt and pepper. \n\nIn a large nonstick skillet over medium-high heat, heat vegetable oil. Remove cod from marinade and season both sides of each filet with salt and pepper. Add fish flesh side-down. Cook until opaque and cooked through, 3 to 5 minutes per side. Let rest 5 minutes before flaking with a fork. \n\nAssemble tacos: Serve fish over grilled tortillas with corn slaw and avocado. Squeeze lime juice on top and garnish with sour cream.',
        image_url: 'https://www.freshcravings.com/wp-content/uploads/2019/09/FC_easyfishtacos-1480x1480@2x.jpg'},
        {id: 6, title: 'Chicken Curry', meal_type: 'Dinner', serving_size: 4, difficulty_level: 'Intermediate', cooking_time_in_minutes: 40, ingredients: 'SPICE BlEND:\n\n1 1/2 tsp ground coriander\n\n1 tsp ground cumin\n\n1/2 tsp turmeric\n\n1/2 tsp fennel seeds, crushed in a small bag with a meat mallet\n\n1/2 tsp ground cinnamon\n\n1/2 tsp ground black pepper\n\n1/4 tsp ground mustard\n\n1/4 tsp ground cloves\n\n---------------------\n\nCURRY:\n\n2 Tbsp olive oil\n\n1 small yellow onion, chopped (1 cup)\n\n4 garlic cloves, minced (1 1/2 Tbsp)\n\n1 Tbsp peeled and minced fresh ginger\n\n1 cup low-sodium chicken broth\n\n3/4 cup drained canned diced tomatoes or peeled, seeded, diced fresh tomatoes\n\nSalt\n\nCayenne pepper, to taste\n\n1 1/2 lbs boneless skinless chicken breasts, diced into 1 1/4-inch cubes\n\n1 tsp cornstarch mixed with 2 tsp water (optional)\n\n1/3 cup heavy cream\n\n2 Tbsp chopped cilantro',
        instructions: 'In a small mixing bowl whisk together all of the spices in the spice blend, set aside. \n\nHeat olive oil in a 12-inch non-stick skillet over medium-high heat. \n\nAdd in onion and saute until slightly golden brown, about 4 - 6 minutes. \n\nAdd in garlic and ginger, saute 30 seconds more then add in spice blend and saute 30 seconds. \n\nPour in chicken broth and tomatoes and bring to a boil, then reduce heat to medium-low, cover and simmer 5 minutes. \n\nPour mixture into a blender then cover with lid and remove lid insert, cover opening with a clean folded kitchen rag. \n\nBlend mixture until well pureed and smooth then return to skillet and heat skillet over medium-high heat. \n\nSeason sauce with salt and cayenne pepper (start with about 1/2 tsp salt and a few dashes cayenne then add more to taste) then add in chicken. \n\nBring to a simmer then reduce heat to medium-low, cover skillet with lid and simmer until chicken has cooked through, stirring occasionally, about 8 -  12 minutes. \n\nDuring the last minute of cooking stir in the cornstarch and water slurry if desired, to thicken sauce slightly (or if needed thin with a little chicken broth). \n\nStir in cream then serve warm with cilantro over basmati rice.',
        image_url: 'https://asapchops.com/wp-content/uploads/2021/03/Easy-Chicken-Curry-square-FS-117.jpg'},
        {id: 7, title: 'Chewy Peanut Butter Brownies', meal_type: 'Dessert', serving_size: 16, difficulty_level: 'Beginner', cooking_time_in_minutes: 40, ingredients: '½ cup peanut butter\n\n⅓ cup margarine, softened\n\n⅔ cup white sugar\n\n½ cup packed brown sugar\n\n2 eggs\n\n½ teaspoon vanilla extract\n\n1 cup all-purpose flour\n\n1 teaspoon baking powder\n\n¼ teaspoon salt',
        instructions: 'Preheat oven to 350 degrees F (175 degrees C ). Grease a 9x9 inch baking pan. \n\nIn a medium bowl, cream together peanut butter and margarine. Gradually blend in the brown sugar, white sugar, eggs, and vanilla; mix until fluffy. Combine flour, baking powder, and salt; stir into the peanut butter mixture until well blended. \n\nBake for 30 to 35 minutes in preheated oven, or until the top springs back when touched. Cool, and cut into 16 squares.',
        image_url: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F05%2F08%2FChewy-Peanut-Butter-Brownies-by-abcdeelishus.jpg'},
        {id: 8, title: 'Brandy Salted Caramel Doughnuts', meal_type: 'Dessert', serving_size: 12, difficulty_level: 'Beginner', cooking_time_in_minutes: 105, ingredients: '2 tsp (7g) dried yeast\n\n2/3 cup (160ml) lukewarm milk\n\n2 2/3 cup (400g) plain flour\n\n2 tbs brown sugar\n\n2 eggs\n\n60g butter, chopped\n\n1 cup caster sugar\n\n1½ tsp mixed spice\n\n½ tsp ground cinnamon\n\n---------------------\n\nBRANDY DULCE CUSTARD:\n\n6 egg yolks\n\n2/3 cup (100g) cornflour\n\n200g dulce de leche\n\n2 cups (500ml) milk\n\n¼ cup (60ml) brandy',
        instructions: 'Combine yeast, milk and 1 tbs flour in a jug. Cover and set aside in a warm place for 10 minutes until frothy. Place remaining flour in an electric mixer fitted with a dough hook. Add yeast mixture, sugar, eggs and 1/2 tsp salt, then knead for 2 minutes or until dough comes together. Add butter, one piece at a time, until combined. Knead for 2 – 3 minutes until dough is soft. Transfer to a greased bowl. Cover and set aside in a warm place for 45 minutes or until doubled in size. \n\nMeanwhile to make the custard, whisk egg yolks and cornflour in a heatproof bowl until smooth. Place Dolce de lece, milk and brandy in a saucepan over medium heat and whisk until combined, bring to a simmer, remove from heat. Pour brandy mixture over egg mixture, whisking until combined. Return mixture to saucepan over medium heat, cook, whisking, for 6 minutes until thick. \n\nPour into a bowl, cover surface with plastic wrap set aside to cool to room temperature. Whisk cool custard until smooth. Whisk to combine, transfer custard mixture to a piping bag fitted with 1.5cm plain nozzle. Knock back donut dough. Divide dough into 12, roll into balls and place on an oiled baking tray. Cover and set aside for a further 20 minutes or until risen slightly. \n\nMeanwhile, combine caster sugar, cinnamon and mixed spice in a large bowl. Half-fill a large saucepan or wok with oil, heat to 170°C (a cube of bread will turn golden in 45 seconds when hot enough). In batches, fry doughnuts, turning, for 3 – 4 minutes until golden. Toss hot donuts in sugar mixture. Repeat with remaining donut and sugar mixtures. Push piping bag nozzle into the side of each doughnut and pipe in custard. Serve warm.',
        image_url: 'https://img.delicious.com.au/LDSQJaQo/w759-h506-cfill/del/2016/09/brandy-salted-caramel-doughnuts-36304-2.jpg'},
        {id: 9, title: 'Authentic Italian Lasagna 🤤', meal_type: 'Dinner', serving_size: 8, difficulty_level: 'Intermediate', cooking_time_in_minutes: 55,
        ingredients: '1 pound sweet Italian sausage\n\n3/4 pound lean ground beef\n\n1/2 cup minced onion\n\n2 cloves garlic, crushed\n\n 1 (28 ounce) can crushed tomatoes\n\n2 (6 ounce) cans tomato paste\n\n2 (6.5 ounce) cans canned tomato sauce\n\1/2 cup water\n\n2 tablespoons white sugar\n\n1  1/2 teaspoons dried basil leave\n\n1/2 teaspoon fennel seeds\n\n1 teaspoon Italian seasoning\n\n1 1/2 teaspoons salt, divided, or to taste\n\1/4 teaspoon ground black\n\n 4 tablespoons chopped fresh parsley\n\n12 lasagna noodles\n\n16 ounces ricotta cheese\n\n1 egg\n\n\3/4 pound mozzarella cheese, sliced\n\3/4 cup grated Parmesan cheese'\n\n',
        instructions: 'In a Dutch oven, cook sausage, ground beef, onion, and garlic over medium heat until well browned. Stir in crushed tomatoes, tomato paste, tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian seasoning, 1 teaspoon salt, pepper, and 2 tablespoons parsley. Simmer, covered, for about 1 1/2 hours, stirring occasionally. \n\nBring a large pot of lightly salted water to a boil. Cook lasagna noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse with cold water. In a mixing bowl, combine ricotta cheese with egg, remaining parsley, and 1/2 teaspoon salt. \n\nPreheat oven to 375 degrees F (190 degrees C). \n\nTo assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13-inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread with one half of the ricotta cheese mixture. Top with a third of mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella, and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with remaining mozzarella and Parmesan cheese Cover with foil: to prevent sticking, either spray foil with cooking spray, or make sure the foil does not touch the cheese. \n\nBake in preheated oven for 25 minutes. Remove foil, and bake an additional 25 minutes. Cool for 15 minutes before serving.'
        image_url: ''
      ]);
    });
};
